In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/Employee.csv")

In [4]:
print("Average Age:",df["Age"].mean())

Average Age: 29.393294648613796

In [5]:
df["Age"].max()

41

In [6]:
df["Age"].min()

22

In [7]:
df["ExperienceInCurrentDomain"].mean()

np.float64(2.905652267354395)

In [8]:
df["LeaveOrNot"].value_counts()

LeaveOrNot
0    3053
1    1600
Name: count, dtype: int64

In [14]:
df = df.dropna()

In [15]:
city_group = df.groupby("City")

In [16]:
city_analysis = city_group.agg({
    "Age": ["mean", "max", "min"],
    "ExperienceInCurrentDomain": ["mean", "max"],
    "PaymentTier": "count"
})

In [17]:
print(city_analysis)

                 Age         ExperienceInCurrentDomain     PaymentTier
                mean max min                      mean max       count
City
Bangalore  29.594255  41  22                  2.924596   7        2228
New Delhi  29.121003  41  22                  2.885048   6        1157
Pune       29.288644  41  22                  2.891167   7        1268

In [18]:
tier_group = df.groupby("PaymentTier")

In [19]:
tier_analysis = tier_group.agg({
    "Age": ["mean", "max", "min"],
    "ExperienceInCurrentDomain": ["mean", "max"],
    "City": "count"
})

In [20]:
print(tier_analysis)

                   Age         ExperienceInCurrentDomain      City
                  mean max min                      mean max count
PaymentTier
1            29.592593  41  22                  2.761317   7   243
2            29.183007  41  22                  2.900871   7   918
3            29.434708  41  22                  2.916953   7  3492

In [21]:
gender_group = df.groupby("Gender")

In [22]:
gender_group = df.groupby("Gender")

gender_analysis = gender_group.agg({
    "Age": ["mean", "max"],
    "ExperienceInCurrentDomain": "mean",
    "City": "count"
})

In [23]:
print(gender_analysis)

             Age     ExperienceInCurrentDomain  City
            mean max                      mean count
Gender
Female  29.41600  41                  2.889067  1875
Male    29.37797  41                  2.916847  2778

In [24]:
multi_analysis = df.groupby(["City", "Gender"]).agg({
    "Age": "mean",
    "ExperienceInCurrentDomain": "mean"
})

In [25]:
print(multi_analysis)

                        Age  ExperienceInCurrentDomain
City      Gender
Bangalore Female  29.817906                   2.939302
          Male    29.500319                   2.918419
New Delhi Female  29.170968                   2.901613
          Male    29.063315                   2.865922
Pune      Female  29.226510                   2.820470
          Male    29.343750                   2.953869

In [26]:
df.corr(numeric_only=True)

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
JoiningYear,1.000000,-0.096078,0.013165,-0.036525,0.181705
PaymentTier,-0.096078,1.000000,0.007631,0.018314,-0.197638
Age,0.013165,0.007631,1.000000,-0.134643,-0.051126
ExperienceInCurrentDomain,-0.036525,0.018314,-0.134643,1.000000,-0.030504
LeaveOrNot,0.181705,-0.197638,-0.051126,-0.030504,1.000000

In [27]:
df.sort_values(by="ExperienceInCurrentDomain", ascending=False).head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
3988,Bachelors,2016,Bangalore,3,38,Female,No,7,0
3989,Bachelors,2015,Pune,2,41,Female,No,7,0
3971,Masters,2014,Bangalore,3,40,Female,No,7,1
3985,Bachelors,2015,Pune,3,34,Male,Yes,7,0
3975,Bachelors,2014,Bangalore,3,39,Male,No,7,1

In [28]:
df.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000